version: "3"
services:    
    elasticsearch:
        image: elasticsearch:7.6.1
        command: discovery.type=single-node
        ports: 
          - 9200:9200
          - 9300:9300
        networks:
          - elk-net
    kibana:
        image: kibana:7.6.1
        ports: 
          - 5601:5601        
        networks:
          - elk-net    
        depends_on:
          - elasticsearch    
    logstash:
        image: docker.elastic.co/logstash/logstash:7.6.1
        ports: 
          - 9600:9600    
        networks:
          - elk-net  
        depends_on:
          - elasticsearch  
    apm: 
        image: store/elastic/apm-server:7.6.1
        ports:
          - 9600:9600
        networks:
          - elk-net
        depends_on:
          - elasticsearch
networks:
      elk-net:
        driver: bridge